---
# Source: elasticsearch/templates/1.3.elasticsearch-service.yml
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-RELEASE-NAME-app
  labels:
    app: elasticsearch
    chart: "elasticsearch-1"
    release: RELEASE-NAME
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: es-http
      protocol: TCP
    - port: 9300
      targetPort: es-transport
      protocol: TCP
  selector:
    app: elasticsearch-RELEASE-NAME-app
---
# Source: elasticsearch/templates/1.2.elasticsearch-deployment.yml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: elasticsearch-RELEASE-NAME-app
  labels:
    app: elasticsearch
    chart: "elasticsearch-1"
    release: RELEASE-NAME
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: elasticsearch-RELEASE-NAME-app
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch-RELEASE-NAME-app
    spec:
      containers:
        - name: elasticsearch-app
          image: "arkadym/elasticsearch-nextcloud:7.6.0"
          imagePullPolicy: IfNotPresent
#          command: ['/bin/sh', '-c', 'while true; do echo hello; sleep 10;done']
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 256Mi
          env:
            - name: discovery.type
              value: single-node
            - name: node.name
              value: "es01"
            - name: cluster.name
              value: "RELEASE-NAME-elasticsearch"
            - name: bootstrap.memory_lock
              value: "true"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-RELEASE-NAME-app
                  key: elasticsearch-password
          ports:
            - name: es-http
              containerPort: 9200
              protocol: TCP
            - name: es-transport
              containerPort: 9300
              protocol: TCP
        #  livenessProbe:
        #    tcpSocket:
        #      port: 9200
        #    initialDelaySeconds: 300
        #    timeoutSeconds: 10
---
# Source: elasticsearch/templates/1.1.elasticsearch-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-RELEASE-NAME-app
  labels:
    app: elasticsearch
    chart: "elasticsearch-1"
    release: RELEASE-NAME
    heritage: Helm
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  elasticsearch-password: "bU9yS0oySWRteQ=="
