## Default values for Elastic Helm Chart.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

## Default values for Elastic
##
replicas: 1

## image configuration.
##
image:
  repository: "arkadym/elasticsearch-nextcloud"
  tag: "7.6.0"
  pullPolicy: "IfNotPresent"

## options
password: "not-a-password"
clusterName: "cluster1"
nodeName: "node1"
javaOpts: ""

## persistent store for files
## pvc - Use k8s persistent volume
## - existingClaim - (non empty) use existing volume, other values are ignored
## - accessMode, size, storageClass (existingClaim must be empty) - create new claim with auto provision
## - storageClass - put "-" for empty (will use default configured by k8s)
persistence:
  enabled: true
  accessMode: "ReadWriteMany"
  size: "20Gi"
#  storageClass: "-"
#  existingClaim: "nextcloud-data"

resources:
  requests:
    memory: "256Mi"
    cpu: "300m"
  limits:
    memory: "1Gi"
    cpu: "1"
    
## Service configuration.
##
service:
  type: "ClusterIP"
#  httpPort: "9200"
#  transportPort: "9300"
      
