## Default values for Redmine Helm Chart.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

## Default values for Redmine
##
app:
  replicas: 1

  ## options
#  password: "not-a-password"

  ## image configuration.
  ##
  image:
    repository: "arkadym/elasticsearch-nextcloud"
    tag: "7.6.0"
    pullPolicy: "IfNotPresent"

  resources:
    requests:
      memory: "256Mi"
      cpu: "300m"
    limits:
      memory: "1Gi"
      cpu: "1"
      
  ## Service configuration.
  ##
  service:
    - type: "ClusterIP"
      targetPort: "es-9200"
      port: "9200"
    - type: "ClusterIP"
      targetPort: "es-9300"
      port: "9300"
      
