apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{- if .Values.app.password }}
  elasticsearch-password: {{ .Values.app.password | b64enc | quote }}
{{- else }}
  elasticsearch-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}