apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.httpPort | default "9200" }}
      targetPort: es-http
      protocol: TCP
    - port: {{ .Values.app.service.transportPort | default "9300" }}
      targetPort: es-transport
      protocol: TCP
  selector:
    app: {{ template "app.fullname" . }}
