name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_IMAGE: arkadym/elasticsearch-nextcloud
        DOCKER_ID: ${{ secrets.DOCKER_ID }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        TAG=$(date +%s)
        docker build Docker --tag $DOCKER_IMAGE:$TAG
        docker login -u $DOCKER_ID -p $DOCKER_TOKEN
        docker push $DOCKER_IMAGE:$TAG
